name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clone
      run: git clone https://github.com/Microsoft/vcpkg.git
    - name: cd
      run: cd vcpkg
    - name: run
      run: sh bootstrap-vcpkg.sh # "./bootstrap-vcpkg.bat" for powershell
    - name: intergrate install
      run: vcpkg integrate install
    - name: install leptonica
      run: vcpkg install leptonica
    - name: back
      run: cd ..
    - name: Run autogen.sh
      run: sh autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
